# action.yml
name: 'XLSX to CSVs'
description: "Convert an XLSX file's sheets to separate CSVs"
inputs:
  input_file:  # id of input
    description: 'xlsx file or directory to convert'
    required: true
    default: 'test.xlsx'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input_file }}