on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert to CSV
        uses: ./
        id: convert
        with:
          input_file: $GITHUB_WORKSPACE/test.xlsx
          output_dir: $GITHUB_WORKSPACE/test
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Daisie Huang
          message: "test convert"
          add: $GITHUB_WORKSPACE/test
          ref: "test"