on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert to CSV
        uses: daisieh/xlsx2csv-action@v1.0
        id: convert
        with:
          input_file: test.xlsx
          output_dir: test
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Daisie Huang
          message: "test convert"
          add: "./test/*"
          ref: "test"